### ISSUE TITLE
update mysql databases on visit webpage

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TC-Unused-Guid-Search-web#3]
I am looking to have unused guid searcher self updated when someone visits the page reading the content of a local git repository on that way the searcher can be hosted somewhere without having to use a server to have the database updated.

**Comment by walter-exit** [comment]
Duplicate of ticket #666. Closed.

**Comment by walter-exit** [comment]
Just kidding mate, I'll help you out.

**Comment by Gacko** [comment]
Done in 94da8e571fec380a27fd43a17584b673ef476633.
